### ISSUE TITLE
Broken due to recent Google Music re-design

### ISSUE THREAD

**Issue by orschiro** [tiliado/nuvola-app-google-play#4]
Dear @fenryxo,

I would like to point you to the [recent](http://www.theverge.com/2015/5/14/8606255/google-play-music-web-redesign) Google Music re-design that broke the latest version of Nuvola Player. It currently looks as follows and fails to load the music library:

![image](https://cloud.githubusercontent.com/assets/170947/7665002/33e13318-fba4-11e4-92f8-39a3ca73e78f.png)

I hope you can update Nuvola to work with the latest design. 

Warmly,

Robert

**Comment by fenryxo** [comment]
Hello @orschiro. This issue is tracked as the bug tiliado/nuvolaplayer#100. Could you subscribe to it? There seems to be a bug in Google Play Music code. Could you [up-vote my bug report at Google Products forum](https://productforums.google.com/forum/#!topic/play/U98y_b4Uxk0;context-place=forum/play)? I hope Google will take it a bit more seriously with the extra votes. Thanks!

**Comment by orschiro** [comment]
@fenryxo 

Thanks! I upvoted your thread on the Google Play Forum and subscribed to the other one on Github. 

Hopefully this will soon be paid attention to. 

Thanks for your engagement!

Robert

**Comment by jxn** [comment]
Any chance this is relevant: https://github.com/twolfson/google-music-webkit/issues/6

**Comment by fenryxo** [comment]
Hello @jxn. This issue is tracked as the bug tiliado/nuvolaplayer#100. Could repost your comment there?
